spring:
  application:
    name: ${SPRING_APPLICATION_NAME:basket-service}

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:basket-service}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:sa}

  cache:
    redis:
      time-to-live: ${CACHE_TTL:60000}